// ================================ // 🏠 HOME IMAGES // Contiene únicamente las rutas de las imágenes // Los títulos y descripciones se cargan dinámicamente // desde los archivos de traducción (language/*.json) // ================================

export const homeImages = [
  { src: "../assets/images/casa/01.webp" },
  { src: "../assets/images/casa/02.webp" },
  { src: "../assets/images/casa/03.webp" },
  { src: "../assets/images/casa/04.webp" },
  { src: "../assets/images/casa/05.webp" },
  { src: "../assets/images/casa/06.webp" },
  { src: "../assets/images/casa/07.webp" },
  { src: "../assets/images/casa/08.webp" },
  { src: "../assets/images/casa/09.webp" },
  { src: "../assets/images/casa/10.webp" },
  { src: "../assets/images/casa/11.webp" },
  { src: "../assets/images/casa/12.webp" },
  { src: "../assets/images/casa/13.webp" },
  { src: "../assets/images/casa/14.webp" },
  { src: "../assets/images/casa/15.webp" },
  { src: "../assets/images/casa/16.webp" },
  { src: "../assets/images/casa/17.webp" },
  { src: "../assets/images/casa/18.webp" },
  { src: "../assets/images/casa/19.webp" },
  { src: "../assets/images/casa/20.webp" },
  { src: "../assets/images/casa/21.webp" },
  { src: "../assets/images/casa/22.webp" },
  { src: "../assets/images/casa/23.webp" },
  { src: "../assets/images/casa/24.webp" },
  { src: "../assets/images/casa/25.webp" },
  { src: "../assets/images/casa/26.webp" },
  { src: "../assets/images/casa/27.webp" },
  { src: "../assets/images/casa/28.webp" },
  { src: "../assets/images/casa/29.webp" },
  { src: "../assets/images/casa/30.webp" },
  { src: "../assets/images/casa/31.webp" },
  { src: "../assets/images/casa/32.webp" },
  { src: "../assets/images/casa/33.webp" },
  { src: "../assets/images/casa/34.webp" },
  { src: "../assets/images/casa/35.webp" },
  { src: "../assets/images/casa/36.webp" },
  { src: "../assets/images/casa/37.webp" },
  { src: "../assets/images/casa/38.webp" },
  { src: "../assets/images/casa/house-plan01.webp" },
  { src: "../assets/images/casa/house-plan02.webp" }
];
